/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dae2fd",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#dae2fd",
        "on-tertiary-container": "#fffbff",
        "on-error": "#ffffff",
        "on-surface-variant": "#3f4850",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#2d1600",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-tint": "#006398",
        "primary-fixed-dim": "#93ccff",
        "on-surface": "#191c1e",
        "tertiary-container": "#ac6200",
        "secondary": "#565e74",
        "on-primary-container": "#fdfcff",
        "tertiary-fixed-dim": "#ffb875",
        "inverse-primary": "#93ccff",
        "primary-fixed": "#cce5ff",
        "on-secondary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "primary": "#006194",
        "on-primary-fixed-variant": "#004b73",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#001d31",
        "surface-variant": "#e0e3e5",
        "tertiary": "#894d00",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "outline-variant": "#bfc7d2",
        "surface-container-low": "#f2f4f6",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed-variant": "#6b3b00",
        "background": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#ffdcc0",
        "surface-container-highest": "#e0e3e5",
        "outline": "#707881",
        "secondary-fixed-dim": "#bec6e0",
        "primary-container": "#007bb9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "32px",
        "base": "4px",
        "xs": "4px",
        "gutter": "20px",
        "md": "16px",
        "sm": "8px",
        "lg": "24px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "code-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
